# -*- coding: utf-8 -*-
"""CONVERSION DE PDFS OCR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbNAztbk1gutDWT_khCaXGEcexzTrjax
"""

import io
import os
import subprocess
from PIL import Image, ImageEnhance
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import PyPDF2
import pytesseract
from pdf2image import convert_from_path
import shutil
from comtypes import client
from docx2pdf import convert as docx_to_pdf_convert
from msoffice2pdf import convert as msoffice_convert

poppler_path = r'D:\Servicio Social Junio- Diciembre- 2025- JPRR\Analisis documentos\OCR\LIBRERIAS\poppler-22.04.0\Library\bin'
pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'
OUTPUT_MASTER_FOLDER_NAME = 'Archivos procesados'
OCR_DPI = 100
TESSERACT_PSM_CONFIG = r'--psm 3'

# --- FUNCIONES DE CONVERSIÓN Y OCR (SIN CAMBIOS) ---

def convert_word_to_pdf(input_path, output_pdf_path):
    try:
        os.makedirs(os.path.dirname(output_pdf_path), exist_ok=True)
        docx_to_pdf_convert(input_path, output_pdf_path)
        print(f"  > '{os.path.basename(input_path)}' convertido a PDF: '{os.path.basename(output_pdf_path)}'.")
        return True
    except Exception as e:
        print(f"  Error al convertir DOCX a PDF con docx2pdf: {e}")
        return False

def convert_excel_pptx_to_pdf(input_path, output_pdf_path):
    try:
        os.makedirs(os.path.dirname(output_pdf_path), exist_ok=True)
        msoffice_convert(source=input_path, output_dir=os.path.dirname(output_pdf_path))
        print(f"  > '{os.path.basename(input_path)}' convertido a PDF: '{os.path.basename(output_pdf_path)}'.")
        return True
    except Exception as e:
        print(f"  Error al convertir XLSX/PPTX a PDF con msoffice2pdf: {e}")
        return False

def convert_image_to_pdf(input_image_path, output_pdf_path):
    try:
        img = Image.open(input_image_path)
        os.makedirs(os.path.dirname(output_pdf_path), exist_ok=True)
        c = canvas.Canvas(output_pdf_path, pagesize=letter)
        img_width, img_height = img.size
        page_width, page_height = letter
        scale_x = page_width / img_width
        scale_y = page_height / img_height
        scale = min(scale_x, scale_y)
        new_width = img_width * scale
        new_height = img_height * scale
        x_offset = (page_width - new_width) / 2
        y_offset = (page_height - new_height) / 2
        c.drawImage(input_image_path, x_offset, y_offset, new_width, new_height)
        c.save()
        print(f"  > '{os.path.basename(input_image_path)}' convertido a PDF: '{os.path.basename(output_pdf_path)}'.")
        return True
    except FileNotFoundError:
        print(f"  Error: Imagen no encontrada en '{input_image_path}'.")
        return False
    except Exception as e:
        print(f"  Error al convertir imagen '{os.path.basename(input_image_path)}' a PDF: {e}")
        return False

def make_searchable(input_pdf_path, output_pdf_path):
    try:
        images = convert_from_path(input_pdf_path, poppler_path=poppler_path, dpi=OCR_DPI)
        ocr_pages = []
        print(f"  > Procesando {len(images)} páginas para OCR...")
        for i, pil_image in enumerate(images):
            print(f"  > Aplicando OCR a página {i + 1} de {len(images)}...")
            ocr_pdf_bytes = pytesseract.image_to_pdf_or_hocr(pil_image, extension='pdf', lang='spa', config=TESSERACT_PSM_CONFIG)
            reader_for_ocr_page = PyPDF2.PdfReader(io.BytesIO(ocr_pdf_bytes))
            ocr_pages.append(reader_for_ocr_page.pages[0])
        pdf_writer = PyPDF2.PdfWriter()
        for page in ocr_pages:
            pdf_writer.add_page(page)
        os.makedirs(os.path.dirname(output_pdf_path), exist_ok=True)
        with open(output_pdf_path, 'wb') as f:
            pdf_writer.write(f)
        print(f"  > OCR completado para '{os.path.basename(input_pdf_path)}'.")
        return True
    except Exception as e:
        print(f"  Error al hacer buscable el PDF '{os.path.basename(input_pdf_path)}': {e}")
        return False

# --- FUNCIÓN PRINCIPAL  ---
def process_files(main_directory):
    """
    Recorre un directorio, clasifica archivos, los convierte a PDF,
    aplica OCR y guarda los resultados en una única subcarpeta central.
    """
    print(f"Estás trabajando en la carpeta principal: '{main_directory}'.")

    # Crea la carpeta de salida central una sola vez
    output_master_dir = os.path.join(main_directory, OUTPUT_MASTER_FOLDER_NAME)
    os.makedirs(output_master_dir, exist_ok=True)

    for root, dirs, files in os.walk(main_directory):
        # Evita procesar la propia carpeta de salida
        if OUTPUT_MASTER_FOLDER_NAME in root.split(os.sep):
            continue

        print(f"\n--- Procesando archivos en la subcarpeta: '{os.path.basename(root)}' ---")

        for filename in files:
            file_path = os.path.join(root, filename)
            name, ext = os.path.splitext(filename)
            ext = ext.lower()

            # Crea un nombre de archivo único para evitar colisiones
            relative_path = os.path.relpath(file_path, main_directory)
            unique_name = relative_path.replace(os.sep, '_').replace('.', '_')
            intermediate_pdf_path = os.path.join(output_master_dir, f"temp_{unique_name}.pdf")
            final_ocr_pdf_path = os.path.join(output_master_dir, f"{unique_name}.pdf")

            print(f"  Analizando '{filename}'...")

            was_original_pdf = False
            conversion_success = False

            # Lógica para manejar el archivo y generar el PDF intermedio en la carpeta master
            if ext == '.pdf':
                intermediate_pdf_path = file_path # Si ya es PDF, su ruta es la misma
                was_original_pdf = True
                print(f"  '{filename}' es un PDF original.")
                conversion_success = True

            elif ext == '.docx':
                conversion_success = convert_word_to_pdf(file_path, intermediate_pdf_path)

            elif ext in ['.xlsx', '.pptx']:
                conversion_success = convert_excel_pptx_to_pdf(file_path, intermediate_pdf_path)

            elif ext in ['.jpg', '.jpeg', '.png']:
                conversion_success = convert_image_to_pdf(file_path, intermediate_pdf_path)

            else:
                print(f"  '{filename}' tiene un formato no soportado ({ext}). Saltando archivo.")
                continue

            if conversion_success:
                print(f"  '{filename}' listo para OCR. Preparando para OCR.")

                # --- APLICACIÓN FORZADA DE OCR ---
                print(f"  Aplicando OCR a '{os.path.basename(intermediate_pdf_path)}'...")

                if make_searchable(intermediate_pdf_path, final_ocr_pdf_path):
                    print(f"  ¡Éxito! '{os.path.basename(intermediate_pdf_path)}' procesado con OCR y guardado como '{os.path.basename(final_ocr_pdf_path)}'.")

                    # Elimina el PDF intermedio si no era un PDF original
                    if not was_original_pdf and os.path.exists(intermediate_pdf_path):
                        try:
                            os.remove(intermediate_pdf_path)
                            print(f"  > PDF intermedio '{os.path.basename(intermediate_pdf_path)}' eliminado.")
                        except OSError as e:
                            print(f"  Advertencia: No se pudo eliminar el PDF intermedio '{os.path.basename(intermediate_pdf_path)}': {e}")
                else:
                    print(f"  ¡Atención! Hubo un problema al aplicar OCR a '{os.path.basename(intermediate_pdf_path)}'. Revisa los errores anteriores.")
            else:
                print(f"  No se pudo convertir '{filename}' a PDF. Saltando archivo.")
                continue

    print(f"\n--- Proceso completado en '{main_directory}'. ---")

if __name__ == "__main__":
    process_files(r'D:\Servicio Social Junio- Diciembre- 2025- JPRR\Analisis documentos\Anexo tecnico')